# Generated by Django 4.1.4 on 2022-12-17 15:52

import cosplay_project.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), cosplay_project.core.validators.validate_only_letters], verbose_name='Username'),
        ),
    ]
