# Generated by Django 4.1.4 on 2022-12-17 16:18

import cosplay_project.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5, 'First Name must have at least 5 letters!'), cosplay_project.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5, 'Last Name must have at least 5 letters!'), cosplay_project.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Username must have at least 5 letters!'), cosplay_project.core.validators.validate_only_letters], verbose_name='Username'),
        ),
    ]
