# Generated by Django 4.1.4 on 2022-12-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
