# Generated by Django 4.1.4 on 2022-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
